server:
  port: 8085
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
spring:
  main:
    allow-bean-definition-overriding: false
  rabbitmq:
    host: 192.168.154.128
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
