spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      lazy-attributes-resolution: true

server:
  port: 8085

feign:
  okhttp:
    enabled: true

hm:
  db:
    database: hm-trade
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
