server:
  port: 8087
spring:
  rabbitmq:
    host: 192.168.3.106  # RabbitMQ 地址
    port: 5672
    virtual-host: /      # 使用默认 vhost
    username: itheima    # 管理员用户
    password: 123321        # 密码
    listener:
      simple:
        acknowledge-mode: auto
feign:
  okhttp:
    enabled: true # 开启 OKHttp 功能
hm:
  swagger:
    title: 搜索服务接口文档
    package: com.hmall.search.controller
  db:
    database: hm-item
