server:
  port: 8087
feign:
  okhttp:
    enabled: true # 开启 OKHttp 功能
  sentinel:
    enabled: true # 开启 Sentinel 熔断降级
hm:
  swagger:
    title: 搜索服务接口文档
    package: com.hmall.search.controller
  db:
    database: hm-item

spring:
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY:sk-859b35c84cf84101ad1d502823d08768}
      base-url: ${DASHSCOPE_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode}
      chat:
        options:
          model: qwen-turbo
          temperature: 0.7
