server:
  port: 8084

feign:
  okhttp:
    enabled: true

hm:
  db:
    database: hm-user
  swagger:
    title: 用户服务接口文档
    package: com.hmall.user.controller
    db:
      database: hm-user
  jwt:
    tokenTTL: 30m
    password: mykey123
    location: classpath:mykey.jks
    alias: mykey
