server:
  port: 8080
hm:
  jwt:
    #location: classpath:hmall.jks
    #alias: hmall
    #password: hmall123
    tokenTTL: 30m
    password: mykey123
    location: classpath:mykey.jks
    alias: mykey
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
spring:
  main:
    web-application-type: reactive
